### ISSUE TITLE
异常点检测算法——LOF（Local Outiler Factor）

### ISSUE THREAD

**Issue by jiajunliu0024** [LeBron-Jian/MachineLearningNote#1]
5） local reachablity density：局部可达密度

　　局部可达密度（local reachablity density）：局部可达密度的定义是基于可达距离的，对于数据点 p，那些跟 点 p的距离小于等于 K-distance(p) 的数据点称为它的 K-nearest-neighbor，记为Nk(p)，数据点p的局部可达密度为它与邻近的数据点的平均可达距离的导数。

上面应该是倒数吧，好像不是导数。

**Comment by LeBron-Jian** [comment]
> 5） local reachablity density：局部可达密度
> 
> 　　局部可达密度（local reachablity density）：局部可达密度的定义是基于可达距离的，对于数据点 p，那些跟 点 p的距离小于等于 K-distance(p) 的数据点称为它的 K-nearest-neighbor，记为Nk(p)，数据点p的局部可达密度为它与邻近的数据点的平均可达距离的导数。
> 
> 上面应该是倒数吧，好像不是导数。

感谢提醒，笔误。不好意思，误导人了。
